-- begin SALES_ORDER
alter table SALES_ORDER add constraint FK_SALES_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references SALES_CUSTOMER(ID)^
create index IDX_SALES_ORDER_CUSTOMER on SALES_ORDER (CUSTOMER_ID)^
-- end SALES_ORDER
-- begin SALES_ORDER_LINE
alter table SALES_ORDER_LINE add constraint FK_SALES_ORDER_LINE_ORDER foreign key (ORDER_ID) references SALES_ORDER(ID)^
alter table SALES_ORDER_LINE add constraint FK_SALES_ORDER_LINE_PRODUCT foreign key (PRODUCT_ID) references SALES_PRODUCT(ID)^
create index IDX_SALES_ORDER_LINE_ORDER on SALES_ORDER_LINE (ORDER_ID)^
create index IDX_SALES_ORDER_LINE_PRODUCT on SALES_ORDER_LINE (PRODUCT_ID)^
-- end SALES_ORDER_LINE

-- begin SALES_AUTOSERVICE
alter table SALES_AUTOSERVICE add constraint FK_SALES_AUTOSERVICE_CITY foreign key (CITY_ID) references SALES_CITY(ID)^
create index IDX_SALES_AUTOSERVICE_CITY on SALES_AUTOSERVICE (CITY_ID)^
-- end SALES_AUTOSERVICE
-- begin SALES_EMPLOYEE
alter table SALES_EMPLOYEE add constraint FK_SALES_EMPLOYEE_AUTOSERVICE foreign key (AUTOSERVICE_ID) references SALES_AUTOSERVICE(ID)^
create index IDX_SALES_EMPLOYEE_AUTOSERVICE on SALES_EMPLOYEE (AUTOSERVICE_ID)^
-- end SALES_EMPLOYEE
-- begin SALES_REPAIR
alter table SALES_REPAIR add constraint FK_SALES_REPAIR_AUTOSERVICE foreign key (AUTOSERVICE) references SALES_AUTOSERVICE(ID)^
alter table SALES_REPAIR add constraint FK_SALES_REPAIR_EMPLOYEE foreign key (EMPLOYEE) references SALES_EMPLOYEE(ID)^
create index IDX_SALES_REPAIR_AUTOSERVICE on SALES_REPAIR (AUTOSERVICE)^
create index IDX_SALES_REPAIR_EMPLOYEE on SALES_REPAIR (EMPLOYEE)^
-- end SALES_REPAIR
-- begin SALES_INDIVIDUALS
alter table SALES_INDIVIDUALS add constraint FK_SALES_INDIVIDUALS_ID foreign key (ID) references SALES_PERSON(ID)^
-- end SALES_INDIVIDUALS
-- begin SALES_LEGAL
alter table SALES_LEGAL add constraint FK_SALES_LEGAL_ID foreign key (ID) references SALES_PERSON(ID)^
-- end SALES_LEGAL
-- begin SALES_AUTOSERVICE_PERSON_LINK
alter table SALES_AUTOSERVICE_PERSON_LINK add constraint FK_AUTPER_AUTOSERVICE foreign key (AUTOSERVICE_ID) references SALES_AUTOSERVICE(ID)^
alter table SALES_AUTOSERVICE_PERSON_LINK add constraint FK_AUTPER_PERSON foreign key (PERSON_ID) references SALES_PERSON(ID)^
-- end SALES_AUTOSERVICE_PERSON_LINK
