alter table SALES_REPAIR add constraint FK_SALES_REPAIR_AUTOSERVICE foreign key (AUTOSERVICE_ID) references SALES_AUTOSERVICE(ID);
create index IDX_SALES_REPAIR_AUTOSERVICE on SALES_REPAIR (AUTOSERVICE_ID);
