alter table SALES_EMPLOYEE add constraint FK_SALES_EMPLOYEE_AUTOSERVICE foreign key (AUTOSERVICE_ID) references SALES_AUTOSERVICE(ID);
create index IDX_SALES_EMPLOYEE_AUTOSERVICE on SALES_EMPLOYEE (AUTOSERVICE_ID);
